import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Smartwatch',
    description: 'Stay connected in style with this sleek and feature-packed smartwatch. Monitors fitness, notifications, and more.',
    price: 199.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'smartwatch modern',
    featured: true,
  },
  {
    id: '2',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in pure audio bliss with these premium wireless headphones. Active noise cancellation for undisturbed listening.',
    price: 249.50,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'headphones wireless',
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and eco-friendly t-shirt made from 100% organic cotton. Soft, breathable, and perfect for everyday wear.',
    price: 29.99,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'tshirt minimalist',
  },
  {
    id: '4',
    name: 'Handcrafted Leather Wallet',
    description: 'A timeless piece, this wallet is handcrafted from genuine leather, offering durability and classic style.',
    price: 75.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'leather wallet',
    featured: true,
  },
  {
    id: '5',
    name: 'Gourmet Coffee Bean Sampler',
    description: 'Explore a world of flavors with our curated sampler pack of gourmet coffee beans from around the globe.',
    price: 45.00,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'coffee beans',
  },
  {
    id: '6',
    name: 'Yoga Mat - Eco Friendly',
    description: 'High-quality, non-slip, eco-friendly yoga mat for your daily practice. Made from sustainable materials.',
    price: 39.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'yoga mat',
  },
  {
    id: '7',
    name: 'Modern Ceramic Vase Set',
    description: 'Add a touch of elegance to your home decor with this set of 3 minimalist ceramic vases.',
    price: 59.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'ceramic vases',
  },
  {
    id: '8',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact yet powerful Bluetooth speaker. Take your music anywhere with rich sound and long battery life.',
    price: 89.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'bluetooth speaker',
    featured: true,
  },
  {
    id: '9',
    name: 'Smart Home Hub',
    description: 'Control all your smart devices from one central hub. Voice-activated and compatible with major ecosystems.',
    price: 129.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'smart hub',
  },
  {
    id: '10',
    name: 'Insulated Travel Mug',
    description: 'Keep your beverages hot or cold for hours with this stylish and durable insulated travel mug. Leak-proof design.',
    price: 24.99,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'travel mug',
  },
  {
    id: '11',
    name: 'Retro Bluetooth Keyboard',
    description: 'Combine vintage aesthetics with modern technology. This mechanical Bluetooth keyboard offers a satisfying typing experience.',
    price: 119.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'retro keyboard',
    featured: true,
  },
  {
    id: '12',
    name: 'Artisan Chocolate Bar Set',
    description: 'Indulge in a selection of handcrafted artisan chocolate bars, featuring unique flavors and high-quality cocoa.',
    price: 35.50,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'chocolate bars',
  },
  {
    id: '13',
    name: 'Compact Fitness Tracker',
    description: 'Monitor your daily activity, sleep patterns, and heart rate with this lightweight and discreet fitness tracker.',
    price: 69.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'fitness tracker',
  },
  {
    id: '14',
    name: 'Linen Blend Throw Pillow',
    description: 'Add comfort and style to your living space with this soft linen blend throw pillow. Available in various colors.',
    price: 32.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'throw pillow',
  },
  {
    id: '15',
    name: 'Ultra-Thin Laptop',
    description: 'Powerful and portable ultra-thin laptop with a stunning display, perfect for work and entertainment on the go.',
    price: 999.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'laptop ultrathin',
    featured: true,
  },
  {
    id: '16',
    name: 'Plush Velvet Cushion Set (2)',
    description: 'Add a touch of luxury and comfort to your living space with this set of two plush velvet cushions.',
    price: 49.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'velvet cushions',
  },
  {
    id: '17',
    name: '4K Gaming Monitor',
    description: 'Experience breathtaking visuals with this 27-inch 4K gaming monitor, featuring high refresh rates and HDR support.',
    price: 449.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'gaming monitor',
  },
  {
    id: '18',
    name: 'Aromatherapy Essential Oil Diffuser',
    description: 'Create a calming atmosphere with this ultrasonic essential oil diffuser. Features mood lighting and auto shut-off.',
    price: 34.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'oil diffuser',
  },
  {
    id: '19',
    name: 'Smart LED Light Strip Kit',
    description: 'Transform your room with customizable RGB LED light strips. App and voice controlled for millions of colors.',
    price: 39.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'led strip',
    featured: true,
  },
  {
    id: '20',
    name: 'Modern Bookshelf - 5 Tier',
    description: 'Stylish and sturdy 5-tier bookshelf, perfect for displaying books, plants, and decor items.',
    price: 129.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'modern bookshelf',
  },
  {
    id: '21',
    name: 'Portable Power Bank 20000mAh',
    description: 'High-capacity 20000mAh power bank to keep your devices charged on the go. Multiple USB ports.',
    price: 59.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'power bank',
  },
  {
    id: '22',
    name: 'Non-Stick Cookware Set (10 pc)',
    description: 'Durable 10-piece non-stick cookware set. Includes frying pans, saucepans, and utensils. PFOA-free.',
    price: 179.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'cookware set',
  },
  {
    id: '23',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with Qi-enabled smartphones and earbuds. Sleek, minimalist design.',
    price: 25.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'wireless charger',
    featured: true,
  },
  {
    id: '24',
    name: 'Memory Foam Bath Mat',
    description: 'Ultra-soft and absorbent memory foam bath mat for a luxurious feel. Non-slip backing for safety.',
    price: 22.50,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'bath mat',
  },
  {
    id: '25',
    name: 'VR Headset - Advanced Edition',
    description: 'Immerse yourself in virtual reality with this advanced VR headset, featuring high-resolution displays and comfortable fit.',
    price: 399.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'vr headset',
  },
  {
    id: '26',
    name: 'Bamboo Cutting Board Set (3)',
    description: 'Eco-friendly set of 3 bamboo cutting boards in various sizes. Durable, knife-friendly, and easy to clean.',
    price: 29.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'cutting boards',
  },
  {
    id: '27',
    name: 'Drone with 4K Camera',
    description: 'Capture stunning aerial footage with this foldable drone equipped with a 4K camera and intelligent flight modes.',
    price: 599.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'drone camera',
    featured: true,
  },
  {
    id: '28',
    name: 'Scented Candle Collection (3 Pack)',
    description: 'Set of three soy wax scented candles: Vanilla Bean, Lavender Fields, and Warm Sandalwood. Long-lasting fragrance.',
    price: 28.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'scented candles',
  },
  {
    id: '29',
    name: 'E-Reader Tablet',
    description: 'Lightweight e-reader tablet with a paper-like display, adjustable warm light, and long battery life.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'ereader tablet',
  },
  {
    id: '30',
    name: 'Blackout Curtains (Pair)',
    description: 'Energy-efficient blackout curtains that block sunlight and reduce noise. Available in multiple colors and sizes.',
    price: 55.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'blackout curtains',
  },
  {
    id: '31',
    name: 'Smart Thermostat',
    description: 'Wi-Fi enabled smart thermostat that learns your preferences and helps save energy. Controllable via app.',
    price: 179.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'smart thermostat',
    featured: true,
  },
  {
    id: '32',
    name: 'Digital Kitchen Scale',
    description: 'Precise digital kitchen scale with a stainless steel platform. Measures in grams, ounces, pounds, and milliliters.',
    price: 19.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'kitchen scale',
  },
  {
    id: '33',
    name: 'Bluetooth Earpods Pro',
    description: 'True wireless Bluetooth earpods with active noise cancellation, transparency mode, and superior sound quality.',
    price: 159.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'earpods pro',
  },
  {
    id: '34',
    name: 'Minimalist Desk Lamp LED',
    description: 'Sleek LED desk lamp with adjustable brightness and color temperature. Eye-caring and energy-efficient.',
    price: 42.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'desk lamp',
  },
  {
    id: '35',
    name: 'Gaming Mouse RGB',
    description: 'High-precision gaming mouse with customizable RGB lighting, programmable buttons, and adjustable DPI.',
    price: 49.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'gaming mouse',
    featured: true,
  },
  {
    id: '36',
    name: 'Weighted Blanket 15lbs',
    description: 'Premium weighted blanket (15lbs) designed to promote relaxation and improve sleep quality. Soft, breathable fabric.',
    price: 89.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'weighted blanket',
  },
  {
    id: '37',
    name: 'Mechanical Keyboard - Compact',
    description: 'Compact 60% mechanical keyboard with hot-swappable switches and RGB backlighting. Perfect for gaming and typing.',
    price: 89.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'mechanical keyboard',
  },
  {
    id: '38',
    name: 'Cordless Stick Vacuum Cleaner',
    description: 'Lightweight and powerful cordless stick vacuum cleaner. Easily converts to a handheld vacuum. Multiple attachments.',
    price: 199.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'stick vacuum',
  },
  {
    id: '39',
    name: 'Streaming Microphone Kit',
    description: 'Professional USB condenser microphone kit for streaming, podcasting, and recording. Includes pop filter and arm stand.',
    price: 79.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'streaming microphone',
    featured: true,
  },
  {
    id: '40',
    name: 'Indoor Herb Garden Kit',
    description: 'Grow fresh herbs year-round with this smart indoor herb garden kit. Features LED grow lights and self-watering system.',
    price: 69.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'herb garden',
  },
  {
    id: '41',
    name: 'Smart Doorbell Camera',
    description: 'HD video doorbell camera with two-way audio, motion detection, and night vision. See and speak to visitors from anywhere.',
    price: 149.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'doorbell camera',
  },
  {
    id: '42',
    name: 'Rustic Wooden Wall Clock',
    description: 'Large rustic wooden wall clock with a vintage design. Silent non-ticking mechanism. Perfect farmhouse decor.',
    price: 45.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'wooden clock',
  },
  {
    id: '43',
    name: 'WiFi Mesh System (3-Pack)',
    description: 'Eliminate dead zones and enjoy seamless whole-home WiFi coverage with this easy-to-set-up mesh system.',
    price: 229.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'wifi mesh',
    featured: true,
  },
  {
    id: '44',
    name: 'Glass Food Storage Containers (Set of 5)',
    description: 'Set of 5 airtight glass food storage containers with locking lids. BPA-free, microwave, oven, and dishwasher safe.',
    price: 39.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'glass containers',
  },
];
