import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Smartwatch',
    description: 'Stay connected in style with this sleek and feature-packed smartwatch. Monitors fitness, notifications, and more.',
    price: 199.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'smartwatch modern',
    featured: true,
  },
  {
    id: '2',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in pure audio bliss with these premium wireless headphones. Active noise cancellation for undisturbed listening.',
    price: 249.50,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'headphones wireless',
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and eco-friendly t-shirt made from 100% organic cotton. Soft, breathable, and perfect for everyday wear.',
    price: 29.99,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'tshirt minimalist',
  },
  {
    id: '4',
    name: 'Handcrafted Leather Wallet',
    description: 'A timeless piece, this wallet is handcrafted from genuine leather, offering durability and classic style.',
    price: 75.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'leather wallet',
    featured: true,
  },
  {
    id: '5',
    name: 'Gourmet Coffee Bean Sampler',
    description: 'Explore a world of flavors with our curated sampler pack of gourmet coffee beans from around the globe.',
    price: 45.00,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'coffee beans',
  },
  {
    id: '6',
    name: 'Yoga Mat - Eco Friendly',
    description: 'High-quality, non-slip, eco-friendly yoga mat for your daily practice. Made from sustainable materials.',
    price: 39.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'yoga mat',
  },
  {
    id: '7',
    name: 'Modern Ceramic Vase Set',
    description: 'Add a touch of elegance to your home decor with this set of 3 minimalist ceramic vases.',
    price: 59.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'ceramic vases',
  },
  {
    id: '8',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact yet powerful Bluetooth speaker. Take your music anywhere with rich sound and long battery life.',
    price: 89.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'bluetooth speaker',
    featured: true,
  },
];
