
import type { Product } from './types';

export const mockProducts: Product[] = [
  // Electronics (15 products)
  {
    id: '1',
    name: 'Elegant Smartwatch X1',
    description: 'Stay connected in style with this sleek smartwatch. Monitors fitness, notifications, and more with a vibrant AMOLED display.',
    price: 219.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'smartwatch fitness',
    featured: true,
  },
  {
    id: '2',
    name: 'AuraSound Noise-Cancelling Headphones',
    description: 'Immerse yourself in pure audio bliss. Active noise cancellation and plush earcups for ultimate comfort.',
    price: 279.50,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'headphones audio',
  },
  {
    id: '3',
    name: 'BlastBox Portable Bluetooth Speaker',
    description: 'Compact yet powerful Bluetooth speaker. Take your music anywhere with rich sound and 12-hour battery life.',
    price: 99.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'bluetooth speaker',
    featured: true,
  },
  {
    id: '4',
    name: 'ConnectSphere Smart Home Hub',
    description: 'Control all your smart devices from one central hub. Voice-activated and compatible with major ecosystems.',
    price: 139.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'smart hub',
  },
  {
    id: '5',
    name: 'NovaBook Ultra-Thin Laptop',
    description: 'Powerful and portable ultra-thin laptop with a stunning 14-inch display, perfect for work and entertainment.',
    price: 1099.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'laptop ultrathin',
    featured: true,
  },
  {
    id: '6',
    name: 'CrystalView 4K Gaming Monitor',
    description: 'Experience breathtaking visuals with this 28-inch 4K gaming monitor, featuring 144Hz refresh rate and HDR support.',
    price: 479.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'gaming monitor',
  },
  {
    id: '7',
    name: 'LumiFlex Smart LED Strip Kit',
    description: 'Transform your room with customizable RGB LED light strips. App and voice controlled for millions of colors and effects.',
    price: 45.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'led strip',
  },
  {
    id: '8',
    name: 'Volta Portable Power Bank 25000mAh',
    description: 'High-capacity 25000mAh power bank to keep your devices charged on the go. PD fast charging and multiple USB ports.',
    price: 69.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'power bank',
  },
  {
    id: '9',
    name: 'QuickCharge Wireless Charging Pad',
    description: 'Fast 15W wireless charging pad compatible with Qi-enabled smartphones and earbuds. Sleek, minimalist design.',
    price: 29.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'wireless charger',
  },
  {
    id: '10',
    name: 'Immersia VR Headset - Pro Edition',
    description: 'Dive into virtual reality with this Pro VR headset, featuring high-resolution displays, wide field of view, and comfortable fit.',
    price: 429.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'vr headset',
  },
  {
    id: '11',
    name: 'AeroShot Drone with 4K Camera & GPS',
    description: 'Capture stunning aerial footage with this foldable drone equipped with a 4K camera, GPS, and intelligent flight modes.',
    price: 649.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'drone camera',
    featured: true,
  },
  {
    id: '12',
    name: 'PageTurn E-Reader Tablet',
    description: 'Lightweight e-reader tablet with a glare-free paper-like display, adjustable warm light, and weeks of battery life.',
    price: 139.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'ereader tablet',
  },
  {
    id: '13',
    name: 'EcoSmart Thermostat Gen 3',
    description: 'Wi-Fi enabled smart thermostat that learns your preferences and helps save energy. Controllable via app or voice.',
    price: 189.00,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'smart thermostat',
  },
  {
    id: '14',
    name: 'PrecisionStrike Gaming Mouse RGB',
    description: 'High-precision gaming mouse with customizable RGB lighting, 12 programmable buttons, and adjustable DPI up to 16000.',
    price: 55.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'gaming mouse',
  },
  {
    id: '15',
    name: 'ProCast Streaming Microphone Kit',
    description: 'Professional USB condenser microphone kit for streaming, podcasting, and recording. Includes pop filter, shock mount, and arm stand.',
    price: 89.99,
    category: 'Electronics',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'streaming microphone',
  },

  // Apparel (15 products)
  {
    id: '16',
    name: 'Organic Cotton Crewneck T-Shirt',
    description: 'Comfortable and eco-friendly t-shirt made from 100% GOTS certified organic cotton. Soft, breathable, and ethically made.',
    price: 32.99,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'tshirt organic',
  },
  {
    id: '17',
    name: "Men's Classic Denim Jeans - Slim Fit",
    description: 'Timeless slim-fit denim jeans crafted for comfort and style. Made with durable, stretch-infused cotton.',
    price: 79.00,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'mens jeans',
  },
  {
    id: '18',
    name: "Women's Floral Print Maxi Dress",
    description: 'Elegant and flowy maxi dress with a vibrant floral print. Perfect for summer occasions and casual outings.',
    price: 65.50,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'womens dress',
  },
  {
    id: '19',
    name: 'Unisex Pullover Hoodie - Fleece Lined',
    description: 'Cozy and warm fleece-lined pullover hoodie. Features a drawstring hood and kangaroo pocket.',
    price: 54.99,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'hoodie fleece',
  },
  {
    id: '20',
    name: 'Performance Athletic Shorts - Quick Dry',
    description: 'Lightweight and breathable athletic shorts with quick-dry technology. Ideal for workouts and sports activities.',
    price: 39.95,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'athletic shorts',
  },
  {
    id: '21',
    name: 'Cashmere Blend Scarf - Soft Touch',
    description: 'Luxuriously soft cashmere blend scarf, perfect for adding warmth and elegance to any outfit.',
    price: 89.00,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'cashmere scarf',
  },
  {
    id: '22',
    name: 'AquaGuard Waterproof Rain Jacket',
    description: 'Stay dry and comfortable with this lightweight, packable, and fully waterproof rain jacket with taped seams.',
    price: 129.99,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'rain jacket',
    featured: true,
  },
  {
    id: '23',
    name: 'Artisan Leather Ankle Boots',
    description: 'Stylish and durable handcrafted leather ankle boots with a comfortable cushioned insole and sturdy outsole.',
    price: 175.00,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'leather boots',
  },
  {
    id: '24',
    name: 'BreezeWay Summer Linen Shirt',
    description: 'Breathable and lightweight linen shirt, perfect for staying cool and stylish during warmer months.',
    price: 48.75,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'linen shirt',
  },
  {
    id: '25',
    name: 'Nordic Wool Knit Beanie Hat',
    description: 'Keep warm with this classic wool knit beanie, featuring a timeless design and comfortable fit.',
    price: 28.00,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'knit beanie',
  },
  {
    id: '26',
    name: 'FlexFit Sports Bra - High Impact',
    description: 'Supportive high-impact sports bra designed for maximum comfort and performance during intense workouts.',
    price: 42.50,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'sports bra',
  },
  {
    id: '27',
    name: "Men's Modern Tailored Suit Jacket",
    description: 'Sophisticated tailored suit jacket crafted from premium wool blend. Perfect for formal occasions or smart-casual wear.',
    price: 249.99,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'suit jacket',
  },
  {
    id: '28',
    name: "Women's Silk Charmeuse Blouse",
    description: 'Elegant and luxurious silk charmeuse blouse with a beautiful drape. A versatile piece for day or night.',
    price: 119.00,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'silk blouse',
  },
  {
    id: '29',
    name: "Kids' Adventure Graphic T-Shirt Pack (3)",
    description: 'Fun and durable pack of three graphic t-shirts for kids, made from soft cotton for all-day comfort.',
    price: 35.99,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'kids tshirts',
  },
  {
    id: '30',
    name: 'Plush Terry Cloth Bath Robe',
    description: 'Wrap yourself in luxury with this incredibly soft and absorbent terry cloth bath robe. Perfect for relaxing.',
    price: 69.95,
    category: 'Apparel',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'bath robe',
  },

  // Accessories (15 products)
  {
    id: '31',
    name: 'Artisan Handcrafted Leather Wallet',
    description: 'A timeless piece, this wallet is handcrafted from full-grain genuine leather, offering durability and classic style.',
    price: 78.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'leather wallet',
    featured: true,
  },
  {
    id: '32',
    name: 'ThermoFlask Insulated Travel Mug',
    description: 'Keep your beverages hot or cold for hours with this stylish and durable insulated travel mug. Leak-proof design.',
    price: 27.99,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'travel mug',
  },
  {
    id: '33',
    name: 'Stella Minimalist Silver Necklace',
    description: 'Delicate and elegant sterling silver necklace with a minimalist pendant. Perfect for everyday wear or layering.',
    price: 45.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'silver necklace',
  },
  {
    id: '34',
    name: 'Prestige Collection Silk Tie',
    description: 'Luxurious 100% silk tie with a classic pattern. Adds a touch of sophistication to any formal attire.',
    price: 59.95,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'silk tie',
  },
  {
    id: '35',
    name: 'ShadeMaster Polarized Aviator Sunglasses',
    description: 'Classic aviator sunglasses with polarized lenses for superior glare reduction and UV protection.',
    price: 69.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'aviator sunglasses',
    featured: true,
  },
  {
    id: '36',
    name: 'UrbanPack Canvas Laptop Backpack',
    description: 'Durable and stylish canvas backpack with a padded laptop compartment and multiple pockets for organization.',
    price: 85.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'laptop backpack',
  },
  {
    id: '37',
    name: 'Heritage Leather Belt - Classic Buckle',
    description: 'Crafted from genuine leather, this belt features a timeless design and a sturdy classic buckle.',
    price: 49.50,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'leather belt',
  },
  {
    id: '38',
    name: 'ChronoLink Stylish Watch Band',
    description: 'Premium stainless steel watch band compatible with most smartwatches. Adjustable and comfortable for all-day wear.',
    price: 38.99,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'watch band',
  },
  {
    id: '39',
    name: 'PocketShield Compact Travel Umbrella',
    description: 'Windproof and lightweight travel umbrella that folds down compactly to fit in your bag or pocket.',
    price: 22.75,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'travel umbrella',
  },
  {
    id: '40',
    name: 'Boho Beaded Friendship Bracelet Set',
    description: 'Set of 5 colorful beaded friendship bracelets, perfect for sharing or stacking for a bohemian look.',
    price: 18.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'beaded bracelets',
  },
  {
    id: '41',
    name: 'Alpine Wool Fedora Hat',
    description: 'Stylish and warm wool fedora hat with a classic brim. Perfect for adding a touch of class to your autumn/winter wardrobe.',
    price: 72.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'fedora hat',
  },
  {
    id: '42',
    name: 'SafeGuard RFID Blocking Card Holder',
    description: 'Slim and secure card holder with RFID blocking technology to protect your cards from unauthorized scans.',
    price: 19.99,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'rfid wallet',
  },
  {
    id: '43',
    name: 'Glamour Nights Elegant Evening Clutch',
    description: 'Sophisticated evening clutch with a satin finish and a detachable chain strap. Perfect for special occasions.',
    price: 65.00,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'evening clutch',
  },
  {
    id: '44',
    name: 'GripTight Phone Grip & Stand',
    description: 'Secure your grip and prop up your phone with this versatile phone grip and stand. Attaches easily to most phones.',
    price: 12.95,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'phone grip',
  },
  {
    id: '45',
    name: 'FindMe Key Finder - Bluetooth Tracker',
    description: 'Never lose your keys again! Attach this Bluetooth tracker and locate your items with your smartphone.',
    price: 24.50,
    category: 'Accessories',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'key finder',
  },

  // Food & Beverage (15 products)
  {
    id: '46',
    name: 'World Explorer Gourmet Coffee Bean Sampler',
    description: 'Explore a world of flavors with our curated sampler pack of 4 unique gourmet coffee beans from around the globe.',
    price: 48.00,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'coffee beans',
  },
  {
    id: '47',
    name: 'Decadence Artisan Chocolate Bar Set (5 Pack)',
    description: 'Indulge in a selection of five handcrafted artisan chocolate bars, featuring unique flavors and high-quality cocoa.',
    price: 38.50,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'chocolate bars',
  },
  {
    id: '48',
    name: 'Zen Garden Organic Herbal Tea Collection',
    description: 'Relax and rejuvenate with this premium collection of 12 organic herbal teas. Beautifully packaged for gifting.',
    price: 32.99,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'herbal tea',
    featured: true,
  },
  {
    id: '49',
    name: 'Inferno Spicy Chili Oil Trio',
    description: 'Ignite your taste buds with this trio of artisanal chili oils, ranging from mild to extra hot.',
    price: 29.95,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'chili oil',
  },
  {
    id: '50',
    name: 'Tuscan Sun Imported Olive Oil & Balsamic Vinegar Set',
    description: 'Premium extra virgin olive oil and aged balsamic vinegar from Italy. Perfect for salads, dipping, and cooking.',
    price: 55.00,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'olive oil',
  },
  {
    id: '51',
    name: 'Sunrise Crunch Small-Batch Granola Mix',
    description: 'Wholesome and delicious small-batch granola made with organic oats, nuts, seeds, and dried fruits.',
    price: 18.75,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'granola mix',
  },
  {
    id: '52',
    name: 'Spice Voyager Exotic Spice Blend Kit',
    description: 'A curated collection of 6 exotic spice blends to elevate your culinary creations. Includes recipe ideas.',
    price: 42.00,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'spice kit',
  },
  {
    id: '53',
    name: 'Golden Nectar Natural Honey Assortment',
    description: 'Discover the richness of natural honey with this assortment of three distinct flavors: Wildflower, Clover, and Orange Blossom.',
    price: 36.50,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'honey assortment',
  },
  {
    id: '54',
    name: 'Midnight Roast Premium Dark Coffee Pods (24 ct)',
    description: 'Intense and flavorful dark roast coffee pods, compatible with most single-serve brewing systems.',
    price: 21.99,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'coffee pods',
  },
  {
    id: '55',
    name: 'Movie Night Gourmet Popcorn Kernels & Seasoning Set',
    description: 'Everything you need for a gourmet popcorn experience: premium kernels and a variety of delicious seasonings.',
    price: 26.80,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'popcorn set',
  },
  {
    id: '56',
    name: 'TrailBlazer Dried Fruit & Nut Medley',
    description: 'A healthy and energizing mix of premium dried fruits and nuts. Perfect for snacking on the go.',
    price: 19.95,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'trail mix',
  },
  {
    id: '57',
    name: 'Hoppy Days Craft Beer Sampler Pack (Non-Alcoholic)',
    description: 'Explore the world of craft non-alcoholic beer with this diverse sampler pack featuring 6 unique brews.',
    price: 33.00,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'craft beer',
  },
  {
    id: '58',
    name: 'PowerUp Vegan Protein Bar Box (12 Bars)',
    description: 'Fuel your day with these delicious and nutritious plant-based protein bars. Variety pack with 3 flavors.',
    price: 28.99,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'protein bars',
  },
  {
    id: '59',
    name: 'Mama Rosa Artisan Pasta Selection',
    description: 'A taste of Italy with this selection of three artisan pasta shapes, made with traditional methods.',
    price: 24.75,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'artisan pasta',
  },
  {
    id: '60',
    name: 'AquaFizz Sparkling Water Variety Pack (24 Cans)',
    description: 'Refresh yourself with this variety pack of natural fruit-flavored sparkling water. Zero calories, zero sugar.',
    price: 29.99,
    category: 'Food & Beverage',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'sparkling water',
  },

  // Sports & Outdoors (15 products)
  {
    id: '61',
    name: 'ZenFlow Yoga Mat - Eco Friendly & Non-Slip',
    description: 'High-quality, non-slip, eco-friendly yoga mat for your daily practice. Made from sustainable TPE material.',
    price: 42.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'yoga mat',
  },
  {
    id: '62',
    name: 'PulseFit Compact Fitness Tracker',
    description: 'Monitor your daily activity, sleep patterns, heart rate, and SpO2 with this sleek and discreet fitness tracker.',
    price: 74.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'fitness tracker',
  },
  {
    id: '63',
    name: 'PowerFlex Resistance Band Set (5 Levels)',
    description: 'Versatile resistance band set with 5 different strength levels. Ideal for home workouts and physical therapy.',
    price: 21.50,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'resistance bands',
  },
  {
    id: '64',
    name: 'HydroPeak Insulated Stainless Steel Water Bottle (32oz)',
    description: 'Keep your drinks ice cold for 24 hours or hot for 12 hours with this double-walled insulated water bottle.',
    price: 31.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'water bottle',
  },
  {
    id: '65',
    name: 'SummitSeeker Lightweight Camping Tent (2 Person)',
    description: 'Easy-to-set-up lightweight camping tent, perfect for backpacking and weekend adventures. Waterproof and durable.',
    price: 149.00,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'camping tent',
    featured: true,
  },
  {
    id: '66',
    name: 'IronGrip Adjustable Dumbbell Set (5-50 lbs)',
    description: 'Space-saving adjustable dumbbell set, easily switch weights from 5 to 50 lbs. Perfect for a full-body workout.',
    price: 329.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'adjustable dumbbell',
  },
  {
    id: '67',
    name: 'TrailBlazer Hiking Boots - Waterproof & Breathable',
    description: 'Conquer any trail with these comfortable, waterproof, and breathable hiking boots. Superior traction and ankle support.',
    price: 165.00,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'hiking boots',
  },
  {
    id: '68',
    name: 'AeroShield Cycling Helmet - MIPS Certified',
    description: 'Lightweight and aerodynamic cycling helmet with MIPS technology for enhanced protection. Multiple vents for airflow.',
    price: 95.75,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'cycling helmet',
  },
  {
    id: '69',
    name: 'PocketRocket Portable Camping Stove',
    description: 'Ultra-light and compact camping stove that boils water in minutes. Ideal for backpacking and emergency kits.',
    price: 48.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'camping stove',
  },
  {
    id: '70',
    name: 'RallyMaster Pickleball Paddle Set (2 Paddles, 4 Balls)',
    description: 'Graphite pickleball paddle set with a honeycomb core for optimal power and control. Includes carrying case.',
    price: 79.99,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'pickleball set',
  },
  {
    id: '71',
    name: 'StrideFree Running Belt with Phone Holder & Water Bottle Loops',
    description: 'Comfortable and adjustable running belt with a secure phone pocket and loops for small water bottles.',
    price: 23.50,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'running belt',
  },
  {
    id: '72',
    name: 'AnglerPro Fishing Rod & Reel Combo',
    description: 'Versatile fishing rod and reel combo suitable for freshwater and light saltwater fishing. Durable and lightweight.',
    price: 88.00,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'fishing rod',
  },
  {
    id: '73',
    name: 'AquaGlide Inflatable Stand-Up Paddleboard (10ft)',
    description: 'Complete inflatable SUP package, includes board, pump, paddle, leash, and backpack. Stable and easy to maneuver.',
    price: 399.00,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'paddleboard inflatable',
  },
  {
    id: '74',
    name: 'EagleEye Compact Binoculars 10x42',
    description: 'High-power 10x42 binoculars with FMC lenses and BaK4 prism for clear and bright images. Waterproof and fog proof.',
    price: 119.95,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'compact binoculars',
  },
  {
    id: '75',
    name: 'SoundTrek Outdoor Bluetooth Speaker - Rugged & Waterproof',
    description: 'Take your tunes anywhere with this rugged, waterproof, and shockproof Bluetooth speaker. Long battery life.',
    price: 65.00,
    category: 'Sports & Outdoors',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'outdoor speaker',
  },

  // Home Goods (15 products)
  {
    id: '76',
    name: 'Sculpted Harmony Modern Ceramic Vase Set (3)',
    description: 'Add a touch of minimalist elegance to your home decor with this set of 3 Scandinavian-inspired ceramic vases.',
    price: 62.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'ceramic vases',
  },
  {
    id: '77',
    name: 'SereneScents Aromatherapy Essential Oil Diffuser',
    description: 'Create a calming atmosphere with this ultrasonic essential oil diffuser. Features mood lighting, timer settings, and auto shut-off.',
    price: 38.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'oil diffuser',
  },
  {
    id: '78',
    name: 'Aether Modern Industrial Bookshelf - 5 Tier',
    description: 'Stylish and sturdy 5-tier bookshelf with a metal frame and rustic wood shelves, perfect for displaying books and decor.',
    price: 139.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'modern bookshelf',
  },
  {
    id: '79',
    name: 'ChefPro Non-Stick Cookware Set (12 pc)',
    description: 'Durable 12-piece non-stick cookware set. Includes frying pans, saucepans, stockpot, and utensils. PFOA-free.',
    price: 199.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'cookware set',
  },
  {
    id: '80',
    name: 'CloudStep Memory Foam Bath Mat - Extra Plush',
    description: 'Ultra-soft and highly absorbent memory foam bath mat for a luxurious spa-like feel. Non-slip backing for safety.',
    price: 26.50,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'bath mat',
    featured: true,
  },
  {
    id: '81',
    name: 'EcoSlice Bamboo Cutting Board Set (3 Sizes)',
    description: 'Eco-friendly set of 3 organic bamboo cutting boards in various sizes. Durable, knife-friendly, and easy to clean.',
    price: 31.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'cutting boards',
  },
  {
    id: '82',
    name: 'LumiGlow Scented Soy Candle Collection (3 Pack)',
    description: 'Set of three premium soy wax scented candles: Vanilla Bean, Lavender Fields, and Warm Sandalwood. Long-lasting fragrance.',
    price: 30.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'scented candles',
  },
  {
    id: '83',
    name: 'Eclipse Blackout Curtains - Thermal Insulated (Pair)',
    description: 'Energy-efficient thermal insulated blackout curtains that block 99% sunlight and reduce noise. Available in multiple colors and sizes.',
    price: 59.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'blackout curtains',
  },
  {
    id: '84',
    name: 'PrecisionChef Digital Kitchen Scale with Tare Function',
    description: 'Precise digital kitchen scale with a stainless steel platform and easy-to-read LCD. Measures in grams, ounces, pounds, and milliliters.',
    price: 21.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'kitchen scale',
  },
  {
    id: '85',
    name: 'FlexiBright Minimalist LED Desk Lamp',
    description: 'Sleek LED desk lamp with adjustable brightness, color temperature, and a flexible gooseneck. Eye-caring and energy-efficient.',
    price: 45.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'desk lamp',
  },
  {
    id: '86',
    name: 'ComfyRest Weighted Blanket - 15lbs Queen Size',
    description: 'Premium 15lbs weighted blanket designed to promote relaxation and improve sleep quality. Soft, breathable cotton cover.',
    price: 95.00,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'weighted blanket',
  },
  {
    id: '87',
    name: 'SwiftClean Cordless Stick Vacuum Cleaner - Lightweight',
    description: 'Lightweight and powerful cordless stick vacuum cleaner with HEPA filter. Easily converts to a handheld vacuum. Multiple attachments.',
    price: 219.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'stick vacuum',
  },
  {
    id: '88',
    name: 'GreenThumb Smart Indoor Herb Garden Kit',
    description: 'Grow fresh herbs year-round with this smart indoor herb garden kit. Features full-spectrum LED grow lights and self-watering system.',
    price: 75.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'herb garden',
  },
  {
    id: '89',
    name: 'TimeKeeper Rustic Wooden Wall Clock - Oversized',
    description: 'Large 24-inch rustic wooden wall clock with a vintage design. Silent non-ticking mechanism. Perfect farmhouse decor.',
    price: 49.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'wooden clock',
  },
  {
    id: '90',
    name: 'StoreFresh Glass Food Storage Containers (Set of 10 with Lids)',
    description: 'Set of 10 airtight glass food storage containers with locking lids. BPA-free, microwave, oven, freezer, and dishwasher safe.',
    price: 44.99,
    category: 'Home Goods',
    image: 'https://placehold.co/600x400.png',
    imageHint: 'glass containers',
    featured: true,
  },
];
